### ISSUE TITLE
What is right bios for DC600?

### ISSUE THREAD

**Issue by atssada** [konkotgit/MSX-DC-600#1]
Hello,

Really appreciated to wonderful project.
Where can I find right bios to burn into the EEPROM?

Best,
Kim.

**Comment by atssada** [comment]
I found its right bios and working nice! Thank you so much!

**Comment by hpx1984** [comment]
> I found its right bios and working nice! Thank you so much!

Hi Atssada

which bios？

**Comment by Pax-nl** [comment]
@atssada 

Which bios/firmware do you use, I use the one from MSXMakers, but it is Spanish, did you found an EN version?

**Comment by Pax-nl** [comment]
I changed the Spanish text to English and the file is available at: https://download.file-hunter.com/System%20ROMs/extensions/TDC600_EN.ROM
